// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PlanificationEntretien.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ListerLesEntretiensChezSoatFeature : object, Xunit.IClassFixture<ListerLesEntretiensChezSoatFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "listing-entretien.feature"
#line hidden
        
        public ListerLesEntretiensChezSoatFeature(ListerLesEntretiensChezSoatFeature.FixtureData fixtureData, PlanificationEntretien_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr"), "Features", "Lister les entretiens chez Soat", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lister les entretiens déjà planifiés")]
        [Xunit.TraitAttribute("FeatureTitle", "Lister les entretiens chez Soat")]
        [Xunit.TraitAttribute("Description", "Lister les entretiens déjà planifiés")]
        public virtual void ListerLesEntretiensDejaPlanifies()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Lister les entretiens déjà planifiés", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 4
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "email",
                            "language",
                            "xp"});
                table1.AddRow(new string[] {
                            "1",
                            "recruteur@soat.fr",
                            "Java",
                            "10"});
#line 5
        testRunner.Given("les recruteurs existants", ((string)(null)), table1, "Etant donné ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "email",
                            "language",
                            "xp"});
                table2.AddRow(new string[] {
                            "1",
                            "candidat@mail.com",
                            "Java",
                            "5"});
#line 8
        testRunner.And("les candidats existants", ((string)(null)), table2, "Et ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "recruteur",
                            "candidat",
                            "horaire"});
                table3.AddRow(new string[] {
                            "1",
                            "recruteur@soat.fr",
                            "candidat@mail.com",
                            "16/04/2019 15:00"});
#line 11
        testRunner.And("les entretiens existants", ((string)(null)), table3, "Et ");
#line hidden
#line 14
        testRunner.When("on liste les tous les entretiens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "recruteur",
                            "candidat",
                            "language",
                            "horaire"});
                table4.AddRow(new string[] {
                            "1",
                            "recruteur@soat.fr",
                            "candidat@mail.com",
                            "Java",
                            "16/04/2019 15:00"});
#line 15
        testRunner.Then("on récupères les entretiens suivants", ((string)(null)), table4, "Alors ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ListerLesEntretiensChezSoatFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ListerLesEntretiensChezSoatFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
